import { ArrowLeft, ArrowRight, Check, Cpu, Database, HardDrive, LoaderCircle, MemoryStick, Network, Rocket, Server as ServerIcon, ShieldCheck, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api, ApiError } from '../api';
import type { Allocation, Egg, EggVariable, Node, Nest, Server, User } from '../types';
import { Loading } from './Common';

type Draft = {
  name: string; description: string; user: string; node: string; allocation: string; nest: string; egg: string;
  dockerImage: string; startup: string; memory: number; swap: number; disk: number; cpu: number; io: number;
  databases: number; allocations: number; backups: number; startOnCompletion: boolean; environment: Record<string, string>;
};

const initialDraft: Draft = { name: '', description: '', user: '', node: '', allocation: '', nest: '', egg: '', dockerImage: '', startup: '', memory: 4096, swap: 0, disk: 20480, cpu: 200, io: 500, databases: 2, allocations: 1, backups: 3, startOnCompletion: true, environment: {} };

const steps = [{ label: 'Identity', hint: 'Name & owner' }, { label: 'Runtime', hint: 'Node & egg' }, { label: 'Resources', hint: 'Compute limits' }, { label: 'Review', hint: 'Confirm deploy' }];

export function Deploy({ onCreated, notify }: { onCreated: (server: Server) => void; notify: (tone: 'success' | 'error' | 'info', title: string, message?: string) => void }) {
  const [step, setStep] = useState(0); const [draft, setDraft] = useState<Draft>(initialDraft); const [users, setUsers] = useState<User[]>([]); const [nodes, setNodes] = useState<Node[]>([]); const [nests, setNests] = useState<Nest[]>([]); const [eggs, setEggs] = useState<Egg[]>([]); const [allocations, setAllocations] = useState<Allocation[]>([]); const [variables, setVariables] = useState<EggVariable[]>([]); const [loading, setLoading] = useState(true); const [deploying, setDeploying] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({});
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));

  useEffect(() => { api.catalog().then((data) => { setUsers(data.users); setNodes(data.nodes); setNests(data.nests); }).catch((error) => notify('error', 'Could not load deployment catalog', error.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!draft.nest) return setEggs([]); api.eggs(Number(draft.nest)).then(setEggs).catch((error) => notify('error', 'Could not load eggs', error.message)); }, [draft.nest]);
  useEffect(() => { if (!draft.node) return setAllocations([]); api.allocations(Number(draft.node)).then((items) => setAllocations(items.filter((item) => !item.assigned))).catch((error) => notify('error', 'Could not load allocations', error.message)); }, [draft.node]);
  useEffect(() => { if (!draft.egg || !draft.nest) return; api.egg(Number(draft.nest), Number(draft.egg)).then((egg) => {
    const dockerImage = typeof egg.docker_images === 'object' ? Object.values(egg.docker_images)[0] : egg.docker_image;
    const vars = egg.relationships?.variables?.data?.map((item) => item.attributes) ?? [];
    setVariables(vars); setDraft((current) => ({ ...current, dockerImage: dockerImage || egg.docker_image, startup: egg.startup, environment: Object.fromEntries(vars.map((item) => [item.env_variable, item.default_value])) }));
  }).catch((error) => notify('error', 'Could not load egg details', error.message)); }, [draft.egg, draft.nest]);

  const selected = useMemo(() => ({ user: users.find((item) => item.id === Number(draft.user)), node: nodes.find((item) => item.id === Number(draft.node)), nest: nests.find((item) => item.id === Number(draft.nest)), egg: eggs.find((item) => item.id === Number(draft.egg)), allocation: allocations.find((item) => item.id === Number(draft.allocation)) }), [draft, users, nodes, nests, eggs, allocations]);

  function validate(currentStep: number) {
    const next: Record<string, string> = {};
    if (currentStep === 0) { if (!draft.name.trim()) next.name = 'Server name is required.'; if (!draft.user) next.user = 'Choose an owner.'; }
    if (currentStep === 1) { if (!draft.node) next.node = 'Choose a node.'; if (!draft.allocation) next.allocation = 'Choose a free allocation.'; if (!draft.nest) next.nest = 'Choose a nest.'; if (!draft.egg) next.egg = 'Choose an egg.'; }
    if (currentStep === 2) { if (draft.memory < 0) next.memory = 'Memory cannot be negative.'; if (draft.disk < 0) next.disk = 'Disk cannot be negative.'; if (draft.cpu < 0) next.cpu = 'CPU cannot be negative.'; }
    setErrors(next); return !Object.keys(next).length;
  }

  function next() { if (validate(step)) setStep((value) => Math.min(3, value + 1)); }
  async function deploy() {
    setDeploying(true);
    try {
      const server = await api.createServer({ name: draft.name, description: draft.description, user: Number(draft.user), node: Number(draft.node), egg: Number(draft.egg), docker_image: draft.dockerImage, startup: draft.startup, environment: draft.environment, limits: { memory: draft.memory, swap: draft.swap, disk: draft.disk, io: draft.io, cpu: draft.cpu }, feature_limits: { databases: draft.databases, allocations: draft.allocations, backups: draft.backups }, allocation: { default: Number(draft.allocation) }, start_on_completion: draft.startOnCompletion });
      notify('success', 'Server deployment started', `${draft.name} is being installed.`); setDraft(initialDraft); onCreated(server);
    } catch (error) { notify('error', 'Deployment failed', error instanceof ApiError ? error.message : 'The server could not be created.'); }
    finally { setDeploying(false); }
  }

  if (loading) return <div className="page"><Loading label="Loading deployment options…" /></div>;
  return <div className="page deploy-page"><div className="page-heading"><div><p className="eyebrow">Application API</p><h1>Deploy a server</h1><p>Create and install a new Pterodactyl workload.</p></div><span className="secure-note"><ShieldCheck size={16} /> Validated before deployment</span></div>
    <div className="stepper">{steps.map((item, index) => <button key={item.label} className={index === step ? 'active' : index < step ? 'complete' : ''} onClick={() => index < step && setStep(index)}><span>{index < step ? <Check size={15} /> : index + 1}</span><div><strong>{item.label}</strong><small>{item.hint}</small></div>{index < steps.length - 1 && <i />}</button>)}</div>
    <div className="deploy-layout"><section className="panel form-panel">
      {step === 0 && <div className="form-section"><div className="section-title"><span><ServerIcon size={19} /></span><div><h2>Server identity</h2><p>Give the workload a clear name and owner.</p></div></div><div className="form-grid"><label className={`field field--wide ${errors.name ? 'field--error' : ''}`}><span>Server name *</span><input value={draft.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Aurora Survival" />{errors.name && <small>{errors.name}</small>}</label><label className="field field--wide"><span>Description</span><textarea value={draft.description} onChange={(event) => update('description', event.target.value)} placeholder="What is this server used for?" rows={3} /></label><label className={`field field--wide ${errors.user ? 'field--error' : ''}`}><span>Owner *</span><select value={draft.user} onChange={(event) => update('user', event.target.value)}><option value="">Select a user</option>{users.map((user) => <option value={user.id} key={user.id}>{user.first_name} {user.last_name} — {user.email}</option>)}</select>{errors.user && <small>{errors.user}</small>}</label></div></div>}
      {step === 1 && <div className="form-section"><div className="section-title"><span><Rocket size={19} /></span><div><h2>Runtime & placement</h2><p>Choose where and how the server will run.</p></div></div><div className="form-grid"><label className={`field ${errors.node ? 'field--error' : ''}`}><span>Node *</span><select value={draft.node} onChange={(event) => { update('node', event.target.value); update('allocation', ''); }}><option value="">Select a node</option>{nodes.map((node) => <option value={node.id} key={node.id} disabled={node.maintenance_mode}>{node.name}{node.maintenance_mode ? ' (maintenance)' : ''}</option>)}</select>{errors.node && <small>{errors.node}</small>}</label><label className={`field ${errors.allocation ? 'field--error' : ''}`}><span>Primary allocation *</span><select value={draft.allocation} onChange={(event) => update('allocation', event.target.value)} disabled={!draft.node}><option value="">{draft.node ? 'Select a free address' : 'Select a node first'}</option>{allocations.map((item) => <option value={item.id} key={item.id}>{item.alias || item.ip}:{item.port}</option>)}</select>{errors.allocation && <small>{errors.allocation}</small>}</label><label className={`field ${errors.nest ? 'field--error' : ''}`}><span>Nest *</span><select value={draft.nest} onChange={(event) => { update('nest', event.target.value); update('egg', ''); }}><option value="">Select a nest</option>{nests.map((nest) => <option value={nest.id} key={nest.id}>{nest.name}</option>)}</select>{errors.nest && <small>{errors.nest}</small>}</label><label className={`field ${errors.egg ? 'field--error' : ''}`}><span>Egg *</span><select value={draft.egg} onChange={(event) => update('egg', event.target.value)} disabled={!draft.nest}><option value="">{draft.nest ? 'Select an egg' : 'Select a nest first'}</option>{eggs.map((egg) => <option value={egg.id} key={egg.id}>{egg.name}</option>)}</select>{errors.egg && <small>{errors.egg}</small>}</label><label className="field field--wide"><span>Docker image</span><input value={draft.dockerImage} onChange={(event) => update('dockerImage', event.target.value)} placeholder="Selected from egg" /></label><label className="field field--wide"><span>Startup command</span><textarea className="mono-input" value={draft.startup} onChange={(event) => update('startup', event.target.value)} rows={2} /></label>{variables.map((variable) => <label className="field" key={variable.env_variable}><span>{variable.name}</span><input value={draft.environment[variable.env_variable] ?? ''} onChange={(event) => update('environment', { ...draft.environment, [variable.env_variable]: event.target.value })} /><small>{variable.env_variable}</small></label>)}</div></div>}
      {step === 2 && <div className="form-section"><div className="section-title"><span><Cpu size={19} /></span><div><h2>Resource limits</h2><p>Set the container’s compute and feature allowance.</p></div></div><div className="limit-grid"><Limit icon={<MemoryStick />} label="Memory" value={draft.memory} unit="MiB" onChange={(value) => update('memory', value)} hint="0 means unlimited" /><Limit icon={<Cpu />} label="CPU limit" value={draft.cpu} unit="%" onChange={(value) => update('cpu', value)} hint="100% = one core" /><Limit icon={<HardDrive />} label="Disk" value={draft.disk} unit="MiB" onChange={(value) => update('disk', value)} hint="Container storage" /><Limit icon={<Rocket />} label="Block IO" value={draft.io} unit="weight" onChange={(value) => update('io', value)} hint="10–1000" /></div><h3 className="subsection-label">Feature limits</h3><div className="limit-grid limit-grid--features"><Limit icon={<Database />} label="Databases" value={draft.databases} unit="max" onChange={(value) => update('databases', value)} /><Limit icon={<Network />} label="Allocations" value={draft.allocations} unit="max" onChange={(value) => update('allocations', value)} /><Limit icon={<ShieldCheck />} label="Backups" value={draft.backups} unit="max" onChange={(value) => update('backups', value)} /></div></div>}
      {step === 3 && <div className="form-section review-section"><div className="section-title"><span><Check size={19} /></span><div><h2>Review deployment</h2><p>Confirm the configuration before creating the server.</p></div></div><div className="review-hero"><span><ServerIcon size={22} /></span><div><h3>{draft.name}</h3><p>{draft.description || 'No description'}</p></div><span className="soft-badge">Ready</span></div><div className="review-grid"><Review icon={<UserRound />} label="Owner" value={selected.user ? `${selected.user.first_name} ${selected.user.last_name}` : '—'} /><Review icon={<HardDrive />} label="Node" value={selected.node?.name ?? '—'} /><Review icon={<Network />} label="Allocation" value={selected.allocation ? `${selected.allocation.alias || selected.allocation.ip}:${selected.allocation.port}` : '—'} /><Review icon={<Rocket />} label="Runtime" value={`${selected.nest?.name ?? ''} / ${selected.egg?.name ?? ''}`} /><Review icon={<MemoryStick />} label="Memory" value={`${draft.memory.toLocaleString()} MiB`} /><Review icon={<Cpu />} label="CPU" value={`${draft.cpu}%`} /><Review icon={<HardDrive />} label="Disk" value={`${draft.disk.toLocaleString()} MiB`} /><Review icon={<Database />} label="Features" value={`${draft.databases} DB · ${draft.backups} backups`} /></div><label className="switch-row"><span><strong>Start after installation</strong><small>Power on automatically when Wings finishes installing.</small></span><input type="checkbox" checked={draft.startOnCompletion} onChange={(event) => update('startOnCompletion', event.target.checked)} /></label></div>}
      <div className="form-navigation">{step > 0 ? <button className="button button--ghost" onClick={() => setStep((value) => value - 1)}><ArrowLeft size={16} /> Back</button> : <span />}{step < 3 ? <button className="button button--primary" onClick={next}>Continue <ArrowRight size={16} /></button> : <button className="button button--primary button--deploy" onClick={deploy} disabled={deploying}>{deploying ? <LoaderCircle className="spin" size={16} /> : <Rocket size={16} />}{deploying ? 'Deploying…' : 'Deploy server'}</button>}</div>
    </section><aside className="deploy-aside"><div className="panel tip-card"><ShieldCheck size={20} /><h3>Before you deploy</h3><p>The owner, egg and allocation must already exist in Pterodactyl. Only free allocations are shown.</p></div><div className="panel estimate-card"><p>Selected capacity</p><strong>{(draft.memory / 1024).toFixed(1)} GB</strong><span>Memory</span><strong>{(draft.disk / 1024).toFixed(1)} GB</strong><span>Storage</span><strong>{draft.cpu}%</strong><span>CPU</span></div></aside></div>
  </div>;
}

function Limit({ icon, label, value, unit, hint, onChange }: { icon: React.ReactNode; label: string; value: number; unit: string; hint?: string; onChange: (value: number) => void }) {
  return <label className="limit-field"><span className="limit-field__icon">{icon}</span><span><strong>{label}</strong>{hint && <small>{hint}</small>}</span><div><input type="number" min={0} value={value} onChange={(event) => onChange(Number(event.target.value))} /><em>{unit}</em></div></label>;
}

function Review({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return <div className="review-item"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>;
}
