import { ChevronDown, Cpu, LayoutGrid, List, MoreVertical, Plus, Search, Server as ServerIcon, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { Server, ServerState } from '../types';
import { formatBytes, formatUptime } from '../lib';
import { EmptyState, Meter, StatusBadge } from './Common';

export function Servers({ servers, query, onOpen, onPower, onDeploy }: { servers: Server[]; query: string; onOpen: (server: Server) => void; onPower: (server: Server, signal: 'start' | 'stop' | 'restart') => void; onDeploy: () => void }) {
  const [filter, setFilter] = useState<'all' | ServerState>('all');
  const [view, setView] = useState<'list' | 'grid'>('list');
  const [localQuery, setLocalQuery] = useState('');
  const [menu, setMenu] = useState<string | null>(null);
  const search = (query || localQuery).toLowerCase();
  const filtered = useMemo(() => servers.filter((server) => (filter === 'all' || server.status === filter) && [server.name, server.id, server.node, server.address].some((value) => value.toLowerCase().includes(search))), [servers, filter, search]);

  return <div className="page">
    <div className="page-heading"><div><p className="eyebrow">Fleet management</p><h1>Servers</h1><p>Monitor and control every workload from one place.</p></div><button className="button button--primary" onClick={onDeploy}><Plus size={17} /> Deploy server</button></div>
    <div className="toolbar"><label className="toolbar-search"><Search size={16} /><input value={localQuery} onChange={(event) => setLocalQuery(event.target.value)} placeholder="Search by name, ID or node" /></label><div className="filter-pills">{(['all', 'running', 'offline', 'error'] as const).map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item === 'all' ? 'All servers' : item}<span>{item === 'all' ? servers.length : servers.filter((server) => server.status === item).length}</span></button>)}</div><button className="button button--ghost filter-button"><SlidersHorizontal size={16} /> Filters</button><div className="view-toggle"><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={17} /></button><button className={view === 'grid' ? 'active' : ''} onClick={() => setView('grid')}><LayoutGrid size={17} /></button></div></div>
    {!filtered.length ? <EmptyState icon={<ServerIcon />} title="No servers found" description="Try a different search or status filter." /> : view === 'list' ?
      <div className="server-table panel"><div className="server-table__head"><span>Server</span><span>Status</span><span>CPU</span><span>Memory</span><span>Storage</span><span>Uptime</span><span /></div>{filtered.map((server) => <div className="server-row" key={server.id} onDoubleClick={() => onOpen(server)}><button className="server-identity" onClick={() => onOpen(server)}><span className="server-icon"><ServerIcon size={18} /></span><span><strong>{server.name}</strong><small>{server.address} · {server.node}</small></span></button><span><StatusBadge state={server.status} /></span><span className="usage-cell"><strong>{server.usage.cpuAbsolute.toFixed(1)}%</strong><Meter value={server.usage.cpuAbsolute} max={server.usage.cpuLimit || 100} /></span><span className="usage-cell"><strong>{formatBytes(server.usage.memoryBytes)}</strong><Meter value={server.usage.memoryBytes} max={server.usage.memoryLimitBytes} tone="violet" /></span><span className="usage-cell"><strong>{formatBytes(server.usage.diskBytes)}</strong><Meter value={server.usage.diskBytes} max={server.usage.diskLimitBytes} tone="amber" /></span><span className="muted">{formatUptime(server.usage.uptime)}</span><span className="row-actions"><button className="button button--small button--secondary" onClick={() => onOpen(server)}>Manage</button><button className="icon-button" onClick={() => setMenu(menu === server.id ? null : server.id)}><MoreVertical size={17} /></button>{menu === server.id && <div className="action-menu"><button onClick={() => onPower(server, server.status === 'running' ? 'restart' : 'start')}>{server.status === 'running' ? 'Restart' : 'Start'}</button>{server.status === 'running' && <button onClick={() => onPower(server, 'stop')}>Stop</button>}</div>}</span></div>)}</div>
      : <div className="server-card-grid">{filtered.map((server) => <article className="server-card" key={server.id}><div className="server-card__head"><span className="server-icon"><ServerIcon size={19} /></span><StatusBadge state={server.status} /></div><h3>{server.name}</h3><p>{server.description || 'No description provided.'}</p><div className="server-address"><span>{server.address}</span><small>{server.node}</small></div><div className="server-card__metric"><span><Cpu size={14} /> CPU</span><strong>{server.usage.cpuAbsolute.toFixed(1)}%</strong><Meter value={server.usage.cpuAbsolute} max={server.usage.cpuLimit || 100} /></div><div className="server-card__metric"><span>Memory</span><strong>{formatBytes(server.usage.memoryBytes)}</strong><Meter value={server.usage.memoryBytes} max={server.usage.memoryLimitBytes} tone="violet" /></div><button className="button button--secondary button--full" onClick={() => onOpen(server)}>Manage server <ChevronDown size={16} /></button></article>)}</div>}
  </div>;
}
