import { CheckCircle2, CircleHelp, Cloud, Container, Copy, ExternalLink, KeyRound, LockKeyhole, MonitorCog, Server, TerminalSquare } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../api';
import { Loading } from './Common';

type Config = Awaited<ReturnType<typeof api.config>>;

export function SettingsPage({ notify }: { notify: (tone: 'success' | 'error' | 'info', title: string, message?: string) => void }) {
  const [config, setConfig] = useState<Config>();
  useEffect(() => { api.config().then(setConfig).catch((error) => notify('error', 'Could not load configuration', error.message)); }, []);
  function copy(value: string) { navigator.clipboard.writeText(value); notify('success', 'Copied to clipboard'); }
  if (!config) return <div className="page"><Loading /></div>;
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">System</p><h1>Connection</h1><p>API gateway configuration and available runtimes.</p></div><span className={`connection-status ${config.mode === 'live' ? 'live' : ''}`}><i />{config.mode === 'live' ? 'Live API connected' : 'Demo environment'}</span></div><div className="settings-grid"><section className="panel settings-main"><div className="settings-section"><div className="section-title"><span><Server size={19} /></span><div><h2>Pterodactyl panel</h2><p>Configured through environment variables so secrets never reach the browser.</p></div></div><div className="setting-row"><span><small>Panel URL</small><strong>{config.panelUrl}</strong></span><button className="icon-button" onClick={() => copy(config.panelUrl)}><Copy size={16} /></button></div><div className="setting-row"><span><small>Client API</small><strong>{config.clientApi ? 'Key configured' : 'Not configured'}</strong></span>{config.clientApi ? <CheckCircle2 className="success-text" size={18} /> : <CircleHelp size={18} />}</div><div className="setting-row"><span><small>Application API</small><strong>{config.applicationApi ? 'Key configured' : 'Not configured'}</strong></span>{config.applicationApi ? <CheckCircle2 className="success-text" size={18} /> : <CircleHelp size={18} />}</div></div><div className="settings-section"><div className="section-title"><span><LockKeyhole size={19} /></span><div><h2>Dashboard security</h2><p>A signed, HTTP-only session protects remote operations.</p></div></div><div className="setting-row"><span><small>Access password</small><strong>{config.passwordProtected ? 'Enabled' : 'Disabled'}</strong></span><span className={config.passwordProtected ? 'soft-badge' : 'warning-badge'}>{config.passwordProtected ? 'Protected' : 'Development only'}</span></div></div></section><aside className="settings-aside"><div className="panel runtime-card"><h3>Run anywhere</h3><div><span><MonitorCog size={18} /></span><p><strong>Desktop</strong><small>Windows and Linux builds</small></p></div><div><span><Container size={18} /></span><p><strong>Docker</strong><small>Self-hosted web dashboard</small></p></div><div><span><TerminalSquare size={18} /></span><p><strong>CLI</strong><small>Automation with pteroctl</small></p></div></div><div className="panel docs-card"><Cloud size={20} /><h3>Environment setup</h3><p>Copy <code>.env.example</code> to <code>.env</code>, add your keys, and restart the app.</p><a href="https://pterodactyl.io" target="_blank" rel="noreferrer">Pterodactyl documentation <ExternalLink size={14} /></a></div><div className="panel security-card"><KeyRound size={18} /><p>Use an admin Client API key on Pterodactyl 1.8+ for both API scopes, or supply a separate Application key.</p></div></aside></div></div>;
}
