import { Crown, Mail, Plus, Search, Shield, UserRound, Users as UsersIcon } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import { relativeTime } from '../lib';
import type { User } from '../types';
import { EmptyState, Loading, Modal } from './Common';

const blank = { email: '', username: '', first_name: '', last_name: '', password: '', root_admin: false };

export function UsersPage({ notify }: { notify: (tone: 'success' | 'error' | 'info', title: string, message?: string) => void }) {
  const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [showCreate, setShowCreate] = useState(false); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false);
  useEffect(() => { api.users().then(setUsers).catch((error) => notify('error', 'Could not load users', error.message)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => users.filter((user) => `${user.first_name} ${user.last_name} ${user.username} ${user.email}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
  async function create() { setSaving(true); try { const user = await api.createUser(form); setUsers((current) => [...current, user]); setShowCreate(false); setForm(blank); notify('success', 'User created', user.email); } catch (error) { notify('error', 'Could not create user', error instanceof Error ? error.message : undefined); } finally { setSaving(false); } }
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Application API</p><h1>Users</h1><p>Manage accounts that can own and access servers.</p></div><button className="button button--primary" onClick={() => setShowCreate(true)}><Plus size={17} /> Create user</button></div><div className="toolbar user-toolbar"><label className="toolbar-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users" /></label><span>{filtered.length} accounts</span></div>{loading ? <Loading /> : filtered.length ? <div className="users-grid">{filtered.map((user) => <article className="user-card" key={user.id}><span className="user-avatar">{user.first_name.charAt(0)}{user.last_name.charAt(0)}</span><div className="user-card__name"><div><h3>{user.first_name} {user.last_name}</h3>{user.root_admin && <span className="admin-badge"><Crown size={11} />Admin</span>}</div><p>@{user.username}</p></div><div className="user-card__meta"><span><Mail size={14} />{user.email}</span><span><Shield size={14} />Joined {relativeTime(user.created_at)}</span></div><button className="button button--secondary button--full">View account</button></article>)}</div> : <EmptyState icon={<UsersIcon />} title="No users found" description="Try a different search." />}
    {showCreate && <Modal title="Create a Pterodactyl user" description="The new account can immediately own deployed servers." onClose={() => setShowCreate(false)} footer={<><button className="button button--ghost" onClick={() => setShowCreate(false)}>Cancel</button><button className="button button--primary" onClick={create} disabled={saving || !form.email || !form.username || !form.first_name || !form.last_name}>{saving ? 'Creating…' : 'Create user'}</button></>}><div className="form-grid"><label className="field"><span>First name *</span><input value={form.first_name} onChange={(event) => setForm({ ...form, first_name: event.target.value })} /></label><label className="field"><span>Last name *</span><input value={form.last_name} onChange={(event) => setForm({ ...form, last_name: event.target.value })} /></label><label className="field field--wide"><span>Email *</span><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="field"><span>Username *</span><input value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></label><label className="field"><span>Password</span><input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Auto-generated if empty" /></label><label className="switch-row field--wide"><span><strong>Administrator</strong><small>Grant full panel access.</small></span><input type="checkbox" checked={form.root_admin} onChange={(event) => setForm({ ...form, root_admin: event.target.checked })} /></label></div></Modal>}
  </div>;
}
